### ISSUE TITLE
Link para Facebook quebrado

### ISSUE THREAD

**Issue by LuwkasLima** [brainwp/cupuacu-theme#1]
Pessoal,

Na pagina de contato temos o seguinte issue (http://grupocupuaçu.org.br/contato/):

![screenshot from 2014-12-14 11 32 23](https://cloud.githubusercontent.com/assets/5949986/5428413/7af33894-8388-11e4-9570-c50b0e17199c.png)

**Comment by diegorojas** [comment]
Lucas, acho que isso não é uma issue. Se for é de suporte, pois isso ai é o conteúdo da página Contato, foi o cliente que colocou isso assim, se copiar e colar o link inteiro vai funcionar no Face. Na real,  eles precisam de orientação.

**Comment by LuwkasLima** [comment]
Okidoki....issue closed
