### ISSUE TITLE
Section Danças Brasileiras

### ISSUE THREAD

**Issue by everaldomatias** [brainwp/cupuacu-theme#2]
@willowmagrini você criou um CPT para isso, certo? Nessa área da Home a ideia é ter uma descrição (que pode estar no options) e essa lista com as danças, penso que pode ser um menu ( wp_nav_menu()) ), assim eles podem administrar quais e quantas devem aparecer na Home.

![print-cupua](https://cloud.githubusercontent.com/assets/1918474/6428231/d3832790-bf78-11e4-8ec9-a9e15de2fc6a.jpg)

**Comment by willowmagrini** [comment]
@everaldomatias  eu pensei em fazer na esquerda aparecer o excerpt da dança selecionada. O que você acha?

**Comment by everaldomatias** [comment]
Opa, acho lindo!
Mas logo depois do the_excerpt() coloque um link tipo "Veja mais>>", ok?

**Comment by willowmagrini** [comment]
Ok.

**Comment by willowmagrini** [comment]
@everaldomatias coloquei o menu com ajax para os cpts dancas brasileiras: http://beta.brasa.art.br/cupuacu/
Você acha que mantemos o texto de abertura?

**Comment by willowmagrini** [comment]
@everaldomatias outra dúvida: Vamos tem uma página de archive-dancas? se sim preciso de um layout.

**Comment by everaldomatias** [comment]
O AJAX ficou top hein!! Depois quero aprender hehe..

Sim, acho que mantém o texto de abertura.

Do archive-dancas, deixa eu ver o que consigo aqui.

**Comment by willowmagrini** [comment]
@everaldomatias se for o caso de fazermos a archive-dancas.php nós abrimos outra issue.
