### ISSUE TITLE
Imagens da Home

### ISSUE THREAD

**Issue by everaldomatias** [brainwp/cupuacu-theme#3]
Essas imagens da Home precisam ser administráveis, o escopo definido para elas é o seguinte:

A cada visita ela traz uma imagem (para cada uma das duas áreas) aleatoriamente e sem repetir. Acho que podemos facilitar e criar uma página chamada Galeria Cupuaçu e então a Home acessa os attachs dessa página para exibir as imagens.

Lembrando que precisa exibir o autor da foto, veja como pode ser um layout disso:

![print-cupua](https://cloud.githubusercontent.com/assets/1918474/6428327/f56a3db8-bf7c-11e4-9cc7-a54309b24036.jpg)

Atualizei também o layout aqui http://brasawp.art.br/html/cupuacu/home.html com as últimas considerações dela. Os menus são gerenciáveis, então a ordem não vai afetar em nada.

**Comment by willowmagrini** [comment]
@matheusgimenez Você pode colocar essa na sua fila? valeu.

**Comment by matheusgimenez** [comment]
Posso sim.

Mas vou deixar organizado isso já: Não seria interessante nesse caso usar a classe de theme options do Odin? Criamos um campo de multi upload de imagens com ele e o autor seria a descrição do attachment.

**Comment by willowmagrini** [comment]
perfeito.

**Comment by everaldomatias** [comment]
Concordo com a Class do Odin!

Manda Brasa dessa forma @matheusgimenez cria uma seção no Options de Imagens da Home e deixa tudo organizado lá.

**Comment by willowmagrini** [comment]
Valeu @matheusgimenez.  @everaldomatias Eu deixei o height das imagens relativos ao width viewport
