### ISSUE TITLE
Finalizar Slider

### ISSUE THREAD

**Issue by everaldomatias** [brainwp/cupuacu-theme#4]
Não sei qual slider usou aqui, mas minha sugestão é que seja o https://github.com/brasadesign/brasa-slider, e no frontend precisamos finalizar o layout como no exemplo abaixo.

![print-cupua](https://cloud.githubusercontent.com/assets/1918474/6428340/875726e6-bf7d-11e4-945f-5358a344ecb7.jpg)

Com esse nosso plugin é fácil gerenciar o slider, adicionando novos, alterar o link..

**Comment by willowmagrini** [comment]
Aqui são posts? eu criei um cpt slides para isso, uso os últimos posts do blog?

**Comment by everaldomatias** [comment]
Usa esse plugin: https://github.com/brasadesign/brasa-slider ele dá uma administração para o cara adicionar qualquer coisa, post, páginam CPT... a lá Brasa.

**Comment by willowmagrini** [comment]
Acertei os tamanhos dos thumbs e as setas, mas deixei esse outro slider por enquanto.

**Comment by willowmagrini** [comment]
slider Brasa em ação!
