### ISSUE TITLE
Créditos do Grupo no Rodapé

### ISSUE THREAD

**Issue by everaldomatias** [brainwp/cupuacu-theme#5]
Esse box, o logo pode ser via CSS, e as demais informações podemos colocar via options.

![print-cupua](https://cloud.githubusercontent.com/assets/1918474/6428346/e57cd07c-bf7d-11e4-9cb0-682df3389cf3.jpg)

**Comment by willowmagrini** [comment]
Ok coloquei um editor, mas não é facil acertar o texto dentro da caixinha, @everaldomatias será que e melhor fazer por linhas com número limitado de caracter?

**Comment by everaldomatias** [comment]
Você diz no caso da pessoa adicionar muitos caracteres?

**Comment by willowmagrini** [comment]
se ela colocar um <p> lá acho que já sai do retângulo
da uma olhada http://beta.brasa.art.br/cupuacu/wp-admin/themes.php?page=odin-options
