### ISSUE TITLE
Criar um Toggle para a página de danças

### ISSUE THREAD

**Issue by willowmagrini** [brainwp/cupuacu-theme#8]
como em 
https://github.com/brasadesign/litoral-sustentavel/blob/options/js/custom.js

**Comment by everaldomatias** [comment]
Olha um wire, usa o layout da page.

![wire](https://cloud.githubusercontent.com/assets/1918474/6485130/22a23b92-c260-11e4-9c7c-bb5db654092b.jpg)

**Comment by willowmagrini** [comment]
OK
